version: '3.1'

services:

  bot:
    image: bot:local
    restart: always
    env_file:
      - .env
    depends_on:
        db:
          condition: service_healthy
          restart: true


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:16.1
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "bot_data", "-U", "admin"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_data

    
